#!/usr/bin/env python3
# ---------------------------------------------------------------------------
# Authored By: Byron Jordan
# Power Supply Engineer
# Advanced Photon Source (APS)
# Argonne National Laboratory
# ---------------------------------------------------------------------------
"""External oscilloscope CSV FFT/PSD + time-domain stability analysis.

Purpose
-------
Analyze one to four *hardware-timed* oscilloscope channels from a CSV export.
The module is intended for external DCBus measurements, but it is generic so
any oscilloscope channel can be analyzed with the same CDCU spectral pipeline.

The analyzer does NOT use CDCU Ethernet polling to manufacture a spectrum.
It expects a uniformly sampled oscilloscope/DAQ record.  A 10 kHz, 100,001-
sample, 10-second record is the default target because it matches the existing
PMM analysis window, but other hardware-timed sample rates/record lengths are
accepted when they are represented by the CSV timestamps or explicit options.

Outputs per channel
-------------------
* FFT PNG
* Welch PSD PNG
* cumulative-RMS PNG
* composite spectral report PNG
* analysis text generated by the existing spectral engine

Run-level outputs
-----------------
* oscilloscope_stability_summary.txt
* oscilloscope_stability_summary.csv

"""
from __future__ import annotations

import argparse
import math
import re
from dataclasses import dataclass
from pathlib import Path
from typing import Dict, List, Optional, Sequence, Tuple

import numpy as np
import pandas as pd

import cdcu_ripple_psd
from cdcu_ripple_bands import BAND_STR

DEFAULT_FS_HZ = 10_000.0
DEFAULT_EXPECTED_SAMPLES = 100_001
MAX_CHANNELS = 4
TIMING_CV_LIMIT = 1.0e-4

TIME_ALIASES = (
    "time_s", "time", "Time", "TIME", "seconds", "Seconds", "t", "X", "x",
)

DCBUS_ALIASES = {
    "MRP": ("DCBus Input Voltage", "V"),
    "PS:DCBusVoltM": ("DCBus Input Voltage", "V"),
    "DCBusVoltM": ("DCBus Input Voltage", "V"),
    "dcbus_v_V": ("DCBus Input Voltage", "V"),
    "Vbus": ("DCBus Input Voltage", "V"),
    "MGPC": ("DCBus Input Current", "A"),
    "PS:DCBusCurrM": ("DCBus Input Current", "A"),
    "DCBusCurrM": ("DCBus Input Current", "A"),
    "dcbus_i_A": ("DCBus Input Current", "A"),
    "Ibus": ("DCBus Input Current", "A"),
}


@dataclass(frozen=True)
class ScopeChannel:
    column: str
    label: str
    unit: str
    reference: Optional[float] = None


def _safe_stem(text: str) -> str:
    """Return a filesystem-safe channel stem."""
    stem = re.sub(r"[^A-Za-z0-9_.-]+", "_", text.strip()).strip("_.")
    return stem or "channel"


def _infer_unit_and_label(column: str) -> Tuple[str, str]:
    """Infer a reasonable display label/unit without changing the source data."""
    if column in DCBUS_ALIASES:
        return DCBUS_ALIASES[column][1], DCBUS_ALIASES[column][0]
    low = column.lower()
    if "volt" in low or low.endswith("_v") or low.startswith("ch") and "v" in low:
        return "V", column
    if "curr" in low or low.endswith("_a") or "amp" in low:
        return "A", column
    return "", column


def parse_channel_spec(spec: str) -> ScopeChannel:
    """Parse COLUMN,LABEL,UNIT[,REFERENCE].

    A comma-delimited format avoids conflicts with EPICS-style column names that
    can contain colons.
    """
    parts = [p.strip() for p in spec.split(",")]
    if len(parts) not in (3, 4) or not all(parts[:3]):
        raise ValueError(
            "Channel syntax is COLUMN,LABEL,UNIT[,REFERENCE], e.g. "
            '"CH1,DCBus Input Voltage,V,40".'
        )
    ref = None
    if len(parts) == 4 and parts[3] != "":
        ref = float(parts[3])
        if not math.isfinite(ref) or ref == 0.0:
            raise ValueError("Channel REFERENCE must be finite and nonzero.")
    return ScopeChannel(parts[0], parts[1], parts[2], ref)


def _resolve_time_column(df: pd.DataFrame, requested: Optional[str]) -> Optional[str]:
    if requested:
        if requested not in df.columns:
            raise ValueError(f"Requested time column not found: {requested}")
        return requested
    for name in TIME_ALIASES:
        if name in df.columns:
            return name
    return None


def _auto_channels(df: pd.DataFrame, time_col: Optional[str]) -> List[ScopeChannel]:
    """Auto-select up to four numeric-looking measurement columns."""
    channels: List[ScopeChannel] = []
    for col in df.columns:
        if col == time_col:
            continue
        numeric = pd.to_numeric(df[col], errors="coerce")
        if numeric.notna().mean() < 0.99:
            continue
        unit, label = _infer_unit_and_label(str(col))
        channels.append(ScopeChannel(str(col), label, unit, None))
        if len(channels) == MAX_CHANNELS:
            break
    if not channels:
        raise ValueError("No numeric oscilloscope channels were found in the CSV.")
    return channels


def prepare_scope_dataframe(
    df: pd.DataFrame,
    *,
    channels: Optional[Sequence[ScopeChannel]] = None,
    time_column: Optional[str] = None,
    sample_rate_hz: Optional[float] = None,
    expected_samples: Optional[int] = None,
    timing_cv_limit: float = TIMING_CV_LIMIT,
) -> Tuple[pd.DataFrame, List[ScopeChannel], float]:
    """Validate a hardware-timed scope record and return a normalized time base.

    If a time column exists, its measured spacing defines Fs and must be highly
    uniform.  If no time column exists, --sample-rate is mandatory because only
    the acquisition hardware/operator can establish the true sampling rate.
    """
    if len(df) < 3:
        raise ValueError("Oscilloscope record must contain at least three samples.")
    if expected_samples is not None and len(df) != int(expected_samples):
        raise ValueError(
            f"Expected exactly {int(expected_samples):,} samples; received {len(df):,}."
        )

    time_col = _resolve_time_column(df, time_column)
    work = df.copy()

    if time_col is not None:
        t = pd.to_numeric(work[time_col], errors="coerce").to_numpy(dtype=float)
        if not np.all(np.isfinite(t)):
            raise ValueError(f"Time column {time_col!r} contains invalid values.")
        dt = np.diff(t)
        if np.any(dt <= 0):
            raise ValueError("Oscilloscope timestamps must be strictly increasing.")
        mean_dt = float(np.mean(dt))
        cv_dt = float(np.std(dt) / mean_dt)
        if cv_dt > timing_cv_limit:
            raise ValueError(
                f"Scope timing is too irregular for direct FFT/PSD: CV(dt)={cv_dt:.6g} "
                f"> {timing_cv_limit:.6g}."
            )
        measured_fs = 1.0 / mean_dt
        if sample_rate_hz is not None:
            rel = abs(measured_fs - float(sample_rate_hz)) / float(sample_rate_hz)
            if rel > 0.005:
                raise ValueError(
                    f"Timestamp-derived Fs={measured_fs:.6f} Hz disagrees with requested "
                    f"Fs={float(sample_rate_hz):.6f} Hz by {rel:.3%}."
                )
        fs = measured_fs
        work.insert(0, "__scope_time_s", t - t[0])
    else:
        if sample_rate_hz is None or not math.isfinite(sample_rate_hz) or sample_rate_hz <= 0:
            raise ValueError(
                "CSV has no recognized time column. Supply --sample-rate with the oscilloscope's "
                "hardware sample rate; the toolkit will not infer timing from row count alone."
            )
        fs = float(sample_rate_hz)
        work.insert(0, "__scope_time_s", np.arange(len(work), dtype=float) / fs)

    selected = list(channels or _auto_channels(work, time_col))
    if not 1 <= len(selected) <= MAX_CHANNELS:
        raise ValueError(f"Select between 1 and {MAX_CHANNELS} oscilloscope channels.")
    seen = set()
    for ch in selected:
        if ch.column in seen:
            raise ValueError(f"Duplicate oscilloscope channel: {ch.column}")
        seen.add(ch.column)
        if ch.column not in work.columns:
            raise ValueError(f"Oscilloscope channel column not found: {ch.column}")
        work[ch.column] = pd.to_numeric(work[ch.column], errors="coerce")
        if work[ch.column].isna().any():
            raise ValueError(f"Oscilloscope channel {ch.column} contains non-numeric/NaN values.")

    cols = ["__scope_time_s"] + [c.column for c in selected]
    return work[cols].copy(), selected, fs


def stability_metrics(values: np.ndarray, time_s: np.ndarray, reference: Optional[float]) -> Dict[str, float | str | None]:
    """Calculate time-domain stability metrics for one oscilloscope channel.

    'Stability' here means variation over the acquired record, not CAEN's 24-hour
    or 7-day specification.  Peak-to-peak and RMS/standard-deviation metrics are
    reported against either an operator reference or the record mean.
    """
    x = np.asarray(values, dtype=float)
    t = np.asarray(time_s, dtype=float)
    mean = float(np.mean(x))
    median = float(np.median(x))
    minimum = float(np.min(x))
    maximum = float(np.max(x))
    pkpk = maximum - minimum
    std = float(np.std(x, ddof=0))
    ac = x - mean
    rms_ac = float(np.sqrt(np.mean(ac * ac)))
    max_abs_dev = float(np.max(np.abs(ac)))

    ref = reference
    ref_label = "operator reference"
    if ref is None or not math.isfinite(ref) or ref == 0.0:
        ref = mean if math.isfinite(mean) and mean != 0.0 else None
        ref_label = "record mean"

    def rel_ppm(v: float) -> Optional[float]:
        return None if ref is None else abs(float(v) / float(ref)) * 1e6

    def rel_pct(v: float) -> Optional[float]:
        return None if ref is None else abs(float(v) / float(ref)) * 100.0

    drift_per_s = None
    drift_ppm_per_s = None
    if len(x) >= 2 and t[-1] > t[0]:
        slope, _intercept = np.polyfit(t, x, 1)
        drift_per_s = float(slope)
        drift_ppm_per_s = None if ref is None else float(slope / abs(ref) * 1e6)

    return {
        "reference": None if ref is None else float(ref),
        "reference_label": ref_label,
        "mean": mean,
        "median": median,
        "min": minimum,
        "max": maximum,
        "peak_to_peak": float(pkpk),
        "std_dev": std,
        "ac_rms": rms_ac,
        "max_abs_deviation_from_mean": max_abs_dev,
        "peak_to_peak_pct": rel_pct(pkpk),
        "peak_to_peak_ppm": rel_ppm(pkpk),
        "ac_rms_ppm": rel_ppm(rms_ac),
        "max_abs_deviation_ppm": rel_ppm(max_abs_dev),
        "linear_drift_per_s": drift_per_s,
        "linear_drift_ppm_per_s": drift_ppm_per_s,
    }


def _fmt(value: Optional[float], digits: int = 6) -> str:
    if value is None or not math.isfinite(float(value)):
        return "N/A"
    return f"{float(value):.{digits}g}"


def write_stability_reports(
    outdir: Path,
    *,
    source_csv: str,
    channels: Sequence[ScopeChannel],
    metrics: Dict[str, Dict[str, object]],
    fs_hz: float,
    n_samples: int,
    duration_s: float,
) -> Tuple[Path, Path]:
    """Write concise human-readable and machine-readable stability summaries."""
    txt_path = outdir / "oscilloscope_stability_summary.txt"
    csv_path = outdir / "oscilloscope_stability_summary.csv"

    lines = [
        "EXTERNAL OSCILLOSCOPE STABILITY SUMMARY",
        "=" * 72,
        f"Source CSV       : {source_csv}",
        f"Sample rate      : {fs_hz:.6f} Hz",
        f"Samples          : {n_samples:,}",
        f"Record span      : {duration_s:.6f} s",
        "",
        "NOTE: Stability values describe this acquired record only; they are not",
        "      equivalent to CAEN 24-hour or 7-day stability specifications.",
        "",
    ]
    rows = []
    for idx, ch in enumerate(channels, start=1):
        m = metrics[ch.column]
        unit = ch.unit or "unit"
        lines.extend([
            f"CHANNEL {idx}: {ch.label}",
            "-" * 72,
            f"CSV column                         : {ch.column}",
            f"Reference                          : {_fmt(m['reference'])} {unit} ({m['reference_label']})",
            f"Mean / median                       : {_fmt(m['mean'])} / {_fmt(m['median'])} {unit}",
            f"Minimum / maximum                  : {_fmt(m['min'])} / {_fmt(m['max'])} {unit}",
            f"Peak-to-peak variation             : {_fmt(m['peak_to_peak'])} {unit}",
            f"Peak-to-peak stability             : {_fmt(m['peak_to_peak_ppm'])} ppm",
            f"Standard deviation                 : {_fmt(m['std_dev'])} {unit}",
            f"AC RMS about mean                  : {_fmt(m['ac_rms'])} {unit}",
            f"AC RMS stability                   : {_fmt(m['ac_rms_ppm'])} ppm",
            f"Max abs deviation from mean        : {_fmt(m['max_abs_deviation_from_mean'])} {unit}",
            f"Max abs deviation                  : {_fmt(m['max_abs_deviation_ppm'])} ppm",
            f"Linear drift                       : {_fmt(m['linear_drift_per_s'])} {unit}/s",
            f"Linear drift                       : {_fmt(m['linear_drift_ppm_per_s'])} ppm/s",
            "",
        ])
        row = {"channel_number": idx, "column": ch.column, "label": ch.label, "unit": ch.unit}
        row.update(m)
        rows.append(row)

    txt_path.write_text("\n".join(lines), encoding="utf-8")
    pd.DataFrame(rows).to_csv(csv_path, index=False)
    return txt_path, csv_path


def analyze_scope_dataframe(
    df: pd.DataFrame,
    *,
    outdir: str,
    channels: Optional[Sequence[ScopeChannel]] = None,
    time_column: Optional[str] = None,
    sample_rate_hz: Optional[float] = None,
    expected_samples: Optional[int] = None,
    load_desc: Optional[str] = None,
    acq_timestamp: Optional[str] = None,
    logo_path: Optional[str] = None,
    sig_threshold_ppm: float = 12.0,
    fft_y_mode: str = "magnitude",
    source_csv: str = "",
) -> Dict[str, dict]:
    """Analyze up to four scope channels with FFT/PSD and record stability."""
    data, selected, fs = prepare_scope_dataframe(
        df,
        channels=channels,
        time_column=time_column,
        sample_rate_hz=sample_rate_hz,
        expected_samples=expected_samples,
    )
    destination = Path(outdir).expanduser().resolve()
    destination.mkdir(parents=True, exist_ok=True)
    t = data["__scope_time_s"].to_numpy(dtype=float)
    duration = float(t[-1] - t[0])
    results: Dict[str, dict] = {}
    stability: Dict[str, Dict[str, object]] = {}

    for idx, ch in enumerate(selected, start=1):
        sub = pd.DataFrame({"time_s": t, ch.column: data[ch.column].to_numpy(dtype=float)})
        mean = float(sub[ch.column].mean())
        ref = ch.reference if ch.reference is not None else (mean if mean != 0.0 else None)
        ref_label = "operator reference" if ch.reference is not None else "operating point (record mean)"
        ch_dir = destination / f"CH{idx}_{_safe_stem(ch.label)}"
        ch_dir.mkdir(parents=True, exist_ok=True)
        comp = ch_dir / f"scope_CH{idx}_{_safe_stem(ch.label)}_report.png"

        result = cdcu_ripple_psd.analyze_series_for_reports(
            df=sub,
            time_col="time_s",
            value_col=ch.column,
            outdir=str(ch_dir),
            ppm_ref=ref,
            ppm_ref_label=ref_label,
            bands=BAND_STR,
            sig_threshold_ppm=sig_threshold_ppm,
            label=ch.label,
            quantity_unit=ch.unit,
            window="hann",
            nperseg=cdcu_ripple_psd.recommended_welch_nperseg(len(sub), target=16384),
            overlap=0.5,
            auto_scale_freq=True,
            load_desc=load_desc,
            acq_timestamp=acq_timestamp,
            logo_path=logo_path,
            composite_png=str(comp),
            file_prefix=f"scope_CH{idx}",
            fft_y_mode=fft_y_mode,
        )
        stability[ch.column] = stability_metrics(
            sub[ch.column].to_numpy(dtype=float), t, ch.reference
        )
        result["stability"] = stability[ch.column]
        result["channel_number"] = idx
        result["scope_label"] = ch.label
        results[ch.column] = result

    txt, csv = write_stability_reports(
        destination,
        source_csv=source_csv,
        channels=selected,
        metrics=stability,
        fs_hz=fs,
        n_samples=len(data),
        duration_s=duration,
    )
    results["_run"] = {
        "fs_hz": fs,
        "n_samples": len(data),
        "duration_s": duration,
        "stability_txt": str(txt),
        "stability_csv": str(csv),
    }
    return results


def analyze_scope_csv(csv_path: str, **kwargs) -> Dict[str, dict]:
    """Load an oscilloscope CSV and analyze 1-4 selected channels."""
    path = Path(csv_path).expanduser().resolve()
    if not path.is_file():
        raise FileNotFoundError(f"Oscilloscope CSV not found: {path}")
    df = pd.read_csv(path)
    outdir = kwargs.pop("outdir", None) or str(path.parent / f"{path.stem}_scope_analysis")
    return analyze_scope_dataframe(df, outdir=outdir, source_csv=str(path), **kwargs)


def _main() -> int:
    p = argparse.ArgumentParser(
        description="External oscilloscope CSV: up to four channels of FFT/PSD + record stability"
    )
    p.add_argument("--csv", required=True, help="Oscilloscope CSV export")
    p.add_argument("--outdir", default=None)
    p.add_argument("--time-column", default=None, help="CSV time column; auto-detected when omitted")
    p.add_argument("--sample-rate", type=float, default=None,
                   help="Hardware sample rate in Hz. Required only when CSV has no time column.")
    p.add_argument("--expected-samples", type=int, default=None,
                   help="Optional exact record-length check, e.g. 100001")
    p.add_argument("--channel", action="append", default=[],
                   help='Repeat 1-4 times: "COLUMN,LABEL,UNIT[,REFERENCE]"')
    p.add_argument("--load-desc", default=None)
    p.add_argument("--fft-y", choices=["magnitude", "percent", "ppm"], default="magnitude")
    p.add_argument("--logo", default=None, help="Optional transparent PNG branding")
    args = p.parse_args()

    channels = [parse_channel_spec(s) for s in args.channel] if args.channel else None
    if channels and len(channels) > MAX_CHANNELS:
        p.error(f"At most {MAX_CHANNELS} --channel arguments are allowed.")

    results = analyze_scope_csv(
        args.csv,
        outdir=args.outdir,
        channels=channels,
        time_column=args.time_column,
        sample_rate_hz=args.sample_rate,
        expected_samples=args.expected_samples,
        load_desc=args.load_desc,
        logo_path=args.logo,
        fft_y_mode=args.fft_y,
    )
    run = results["_run"]
    n_channels = len([k for k in results if not k.startswith("_")])
    print(f"Oscilloscope analysis complete: {n_channels} channel(s)")
    print(f"  Fs       : {run['fs_hz']:.6f} Hz")
    print(f"  samples  : {run['n_samples']:,}")
    print(f"  duration : {run['duration_s']:.6f} s")
    print(f"  stability: {run['stability_txt']}")
    return 0


if __name__ == "__main__":
    raise SystemExit(_main())
